"""Minimal Arclasp + LangChain example.

Install the optional dependency with:

    pip install "arclasp[langchain]"

This example uses a local LangChain Runnable so it does not require an LLM
provider key. Running it still contacts the configured Arclasp backend because
Arclasp governance decisions are backend-authoritative. Backend approval,
denial, receipt creation, and verification results are generated by Arclasp;
this file does not fabricate those outcomes.
"""

from __future__ import annotations

import asyncio
import os
from typing import Any

import arclasp
from arclasp.langchain import govern


def _require_api_key() -> str:
    try:
        return os.environ["ARCLASP_API_KEY"]
    except KeyError as exc:
        raise SystemExit("Set ARCLASP_API_KEY before running this example.") from exc


def build_chain():
    try:
        from langchain_core.runnables import RunnableLambda
    except ImportError as exc:
        raise SystemExit(
            'Install the LangChain extra first: pip install "arclasp[langchain]"'
        ) from exc

    async def prepare_commitment(inputs: dict[str, Any]) -> dict[str, Any]:
        return {
            "vendor": inputs["vendor"],
            "amount_usd": inputs["amount_usd"],
            "ready_to_commit": True,
        }

    return RunnableLambda(prepare_commitment)


async def main() -> None:
    arclasp.init(api_key=_require_api_key())
    governed = govern(
        build_chain(),
        chain_name="example-langchain-vendor-review",
        metadata={"example": "langchain_minimal"},
    )
    result = await governed.ainvoke({"vendor": "Example Vendor", "amount_usd": 2500})
    print(result)


if __name__ == "__main__":
    asyncio.run(main())
