"""Minimal Arclasp + MCP tool-boundary example.

Install the optional dependency with:

    pip install "arclasp[mcp]"

The MCP adapter governs a tool invocation before forwarding to your handler.
This standalone example uses a local handler for clarity. Running it contacts
the configured Arclasp backend; approval, denial, receipt, and verification
outcomes are generated by Arclasp, not fabricated here.
"""

from __future__ import annotations

import asyncio
import os
from typing import Any

import arclasp
from arclasp.mcp import ArclaspMcpAdapter


def _require_api_key() -> str:
    try:
        return os.environ["ARCLASP_API_KEY"]
    except KeyError as exc:
        raise SystemExit("Set ARCLASP_API_KEY before running this example.") from exc


async def local_handler(tool_name: str, arguments: dict) -> dict[str, Any]:
    return {"tool": tool_name, "accepted": True, "arguments": arguments}


async def main() -> None:
    arclasp.init(api_key=_require_api_key())
    async with arclasp.Chain(
        "example-mcp-tool-call",
        metadata={"example": "mcp_minimal"},
    ) as chain:
        adapter = ArclaspMcpAdapter(chain=chain, agent_name="example-mcp-server")
        result = await adapter.handle_tool_call(
            tool_name="prepare_vendor_commitment",
            arguments={"vendor": "Example Vendor", "amount_usd": 2500},
            handler=local_handler,
        )
        print(result)


if __name__ == "__main__":
    asyncio.run(main())
